### ISSUE TITLE
tray icon missing

### ISSUE THREAD

**Issue by zenitogr** [Bamboooz/magnetar#1]
I think it had a tray icon? now I see no tray icon but magnetar works with ctrl+shift+p?

**Comment by Bamboooz** [comment]
Yes, Ctrl + Shift + P should open magnetar, and im not sure why the tray icon isn't appearing for you. Can you give more details on what environment you are using, windows version, magnetar version etc.?

**Comment by Bamboooz** [comment]
Just published a new release for magnetar which now uses tauri v2. It is possible that it was an issue of tauri v1 (some unsolved bug which got fixed in v2). You might want to check if it works now.
